apiVersion: v1
kind: DeploymentConfig
metadata:
  name: springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image:  rsthakur83/springboot
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
